export interface Listing {
  id: string
  name: string
  tagline: string
  description: string
  illustration: string
  photo?: string
  practical: string | null
}

export interface ListingCategory {
  category: string
  spotIllustration: string
  items: Listing[]
}

export const listings: ListingCategory[] = [
  {
    category: 'Culture',
    spotIllustration: '/illustrations/spot-museums.svg',
    items: [
      {
        id: 'folk-art',
        name: 'Museum of International Folk Art',
        tagline: 'One of the best small museums in the country.',
        description: "The largest collection of Folk Art in the country. Crazy permanent collection with unique rotating exhibits. Great place to get lost. Owen worked here in college!",
        illustration: '/illustrations/listings/folk-art.svg',
        photo: '/images/activities/Museum of International Folk Art.jpg',
        practical: 'On Museum Hill. 15 min drive or bus from downtown.',
      },
      {
        id: 'georgia-okeeffe-museum',
        name: "Georgia O'Keeffe Museum",
        tagline: "Wonderful O'Keeffe collection.",
        description: "The only museum in the world dedicated solely to O'Keeffe's work. The permanent collection spans her entire career and includes layers of context. The building itself is also beautiful.",
        illustration: '/illustrations/listings/georgia-okeeffe-museum.svg',
        photo: "/images/activities/Georgia O'Keeffe Museum.jpg",
        practical: 'On Johnson St, a short walk from the Plaza.',
      },
      {
        id: 'santa-fe-opera',
        name: 'Santa Fe Opera',
        tagline: "Open-air opera in the mountains.",
        description: "The open-air theater sits on a ridge with views of the Jemez and Sangre de Cristo ranges. The season runs July through August. Highly recommended if you can get tickets.",
        illustration: '/illustrations/listings/santa-fe-opera.svg',
        photo: '/images/activities/Santa Fe Opera.jpg',
        practical: 'About 20 min north of Santa Fe. Check the schedule at santafeopera.org.',
      },
      {
        id: 'site-santa-fe',
        name: 'SITE Santa Fe',
        tagline: 'Unique contemporary art museum.',
        description: "SITE always has wonderful contemporary and installation art work. Worth checking what's up during your visit.",
        illustration: '/illustrations/listings/site-santa-fe.svg',
        photo: '/images/activities/SITE Santa Fe.webp',
        practical: 'In the Railyard district. Easy walk from many hotels.',
      },
      {
        id: 'canyon-road',
        name: 'Canyon Road',
        tagline: 'A mile of galleries and gardens.',
        description: "A historic road lined with galleries, studios, and one very good coffee shop. We recommend walking the whole thing while taking time to smell the roses.",
        illustration: '/illustrations/listings/canyon-road.svg',
        photo: '/images/activities/Canyon Road.jpg',
        practical: 'Easy walk from downtown. Mostly flat.',
      },
      {
        id: 'indian-arts-culture',
        name: 'Museum of Indian Arts and Culture',
        tagline: 'Southwest indigenous art, ancient to contemporary.',
        description: "A serious collection covering the art and history of Southwest indigenous peoples, spanning from prehistoric through living artists. On Museum Hill alongside the Folk Art museum, so easy to combine both in a morning. One of the better museums in Santa Fe that most visitors skip.",
        illustration: '/illustrations/listings/indian-arts-culture.svg',
        photo: '/images/activities/Museum of Indian Arts and Culture.jpg',
        practical: 'On Museum Hill. 15 min drive from downtown — pair it with the Folk Art museum.',
      },
      {
        id: 'bug-museum',
        name: 'Reptile and Bug Museum',
        tagline: 'Live reptiles, live bugs.',
        description: "Very wholesome museum in the mall with collections of reptiles and insects. Sleeper hit. The staff know their animals and will tell you about them at length.",
        illustration: '/illustrations/listings/bug-museum.svg',
        photo: '/images/activities/Santa Fe Reptile and Bug Museum.webp',
        practical: 'South side of Santa Fe. Need to drive.',
      },
      {
        id: 'photo-eye',
        name: 'photo-eye Bookstore',
        tagline: 'Legendary photobook store.',
        description: "photo-eye has been a destination for photography books since 1979. The selection is extraordinary — new releases, rare monographs, out-of-print finds. Even if you don't buy anything, it's the kind of place you want to exist. Owen also worked here for many years.",
        illustration: '/illustrations/listings/photo-eye.svg',
        photo: '/images/activities/photo-eye Bookstore.jpg',
        practical: 'Off of Rufina Circle near Meow Wolf.',
      },
      {
        id: 'loretto-chapel',
        name: 'Loretto Chapel',
        tagline: 'The miraculous staircase.',
        description: "A small Gothic chapel built in the 1870s, famous for its spiral staircase: a piece of joinery that has no visible means of support and, depending on who you ask, no natural explanation. The chapel is now deconsecrated and operates as a museum.",
        illustration: '/illustrations/listings/loretto-chapel.svg',
        photo: '/images/activities/Loretto Chapel.jpg',
        practical: 'A short walk from the Plaza. Small admission fee.',
      },
    ],
  },
  {
    category: 'Outdoors',
    spotIllustration: '/illustrations/spot-outdoors.svg',
    items: [
      {
        id: 'ten-thousand-waves-spa',
        name: 'Ten Thousand Waves',
        tagline: 'Japanese mountain spa.',
        description: "It's kind of crazy that Santa Fe has a Japanese spa. They no longer have day passes for the main tubs but you can still book private hot tubs or massages/treatments. Very relaxing and unique experience.",
        illustration: '/illustrations/listings/ten-thousand-waves-spa.svg',
        photo: '/images/activities/Ten Thousand Waves.jpg',
        practical: '15 min drive up Artist Rd. Reserve online, often weeks ahead.',
      },
      {
        id: 'diablo-canyon',
        name: 'Diablo Canyon',
        tagline: 'Volcanic basalt, the Rio Grande, almost no one else.',
        description: "A recreation area near Española where the Rio Grande cuts through dark basalt canyon walls. The hike along the river is easy and very beautiful. We used to go here for weekend camping trips and hikes frequently. This is where Esme learned to swim.",
        illustration: '/illustrations/listings/diablo-canyon.svg',
        photo: '/images/activities/Diablo Canyon.avif',
        practical: 'About 30 min north of Santa Fe. Bring water and sun protection.',
      },
      {
        id: 'ski-basin',
        name: 'Ski Basin',
        tagline: 'Worth it for the drive alone.',
        description: "The road up to the Santa Fe Ski Basin is one of the best easy drives in New Mexico — you climb from 7,000 to over 10,000 feet in 16 miles through aspen and spruce. There are hiking trails at the top and views in every direction. In July the wildflowers are out.",
        illustration: '/illustrations/listings/ski-basin.svg',
        photo: '/images/activities/Ski Basin.jpg',
        practical: "Drive up Hyde Park Road. Bring layers, it's 20 degrees cooler at the top.",
      },
      {
        id: 'monte-sol',
        name: 'Monte Sol',
        tagline: 'Easy hike, good views back over the city.',
        description: "A relatively short and accessible hike in the foothills south of town with rewarding views of Santa Fe and the Jemez Mountains to the west. Not as dramatic as the Ski Basin trails but much closer to the city. It's amazing how quite it is at the top.",
        illustration: '/illustrations/listings/monte-sol.svg',
        photo: '/images/activities/Monte Sol.jpg',
        practical: 'Trailhead off Old Santa Fe Trail Rd. 2–3 hours round trip.',
      },
      {
        id: 'dale-ball-trails',
        name: 'Dale Ball Trails',
        tagline: 'The city trail network. No drive required.',
        description: "A network of well-maintained trails in the foothills just east of downtown, accessible on foot from most hotels near Canyon Road. Good for an early morning run or a casual hike without committing to a drive.",
        illustration: '/illustrations/listings/dale-ball-trails.svg',
        photo: '/images/activities/Dale Ball Trails.webp',
        practical: 'Trailhead off Upper Canyon Rd.',
      },
      {
        id: 'audubon-center',
        name: 'Randall Davey Audubon Center',
        tagline: 'Birding and trails at the edge of the city.',
        description: "A wildlife sanctuary tucked into the foothills at the top of Canyon Road. Has a strong beaver communtiy.",
        illustration: '/illustrations/listings/audubon-center.svg',
        photo: '/images/activities/Randall Davey Audubon Center.jpg',
        practical: 'At the top of Canyon Road. Free to walk the grounds.',
      },
    ],
  },
  {
    category: 'Food',
    spotIllustration: '/illustrations/spot-food.svg',
    items: [
      {
        id: 'el-chile-toreado',
        name: 'El Chile Toreado',
        tagline: 'Our favorite food truck.',
        description: "A small, unassuming spot that most tourists walk past. Do not walk past it. Their burritos haunt me in my dreams. (— Owen)",
        illustration: '/illustrations/listings/el-chile-toreado.svg',
        photo: '/images/activities/El Chile Toreado.webp',
        practical: 'Small, cash-preferred, closes early. Breakfast/lunch.',
      },
      {
        id: 'the-pantry',
        name: 'The Pantry',
        tagline: 'The classic Santa Fe diner.',
        description: "A classic New Mexican diner that has been feeding Santa Fe since 1948. Breakfast all day, huge portions, green and red chile on everything.",
        illustration: '/illustrations/listings/the-pantry.svg',
        photo: '/images/activities/The Pantry.jpg',
        practical: 'On Cerrillos Rd. Breakfast and lunch only.',
      },
      {
        id: 'izunami',
        name: 'Izanami',
        tagline: 'Japanese izakaya on the mountain.',
        description: "The restaurant at Ten Thousand Waves serves world class Japanese izakaya food. It's a good dinner even if you're not staying at the spa. Reservations strongly advised. We love the Wagyu Beef Ishiyaki.",
        illustration: '/illustrations/listings/izunami.svg',
        photo: '/images/activities/Izanami.jpg',
        practical: '15 min drive up the mountain. Reserve ahead.',
      },
      {
        id: 'harrys-road-house',
        name: "Harry's Road House",
        tagline: 'New Mexican comfort food.',
        description: "Harry's is the place you go when you want green chile on everything and you want it to be good. A Santa Fe institution. Last time we were there they picked the mint for the mojitos from the courtyard.",
        illustration: '/illustrations/listings/harrys-road-house.svg',
        photo: "/images/activities/Harry's Road House.jpg",
        practical: 'Old Las Vegas Highway — a short drive from downtown.',
      },
      {
        id: 'the-shed',
        name: 'The Shed',
        tagline: 'New Mex \& Margeritas',
        description: "The Shed occupies a courtyard compound from the 17th century and has been serving New Mexican food since 1953. The red chile is famous for a reason. Lunch lines get long — plan around it or go at opening.",
        illustration: '/illustrations/listings/the-shed.svg',
        photo: '/images/activities/The Shed.jpg',
        practical: 'Closed Sundays. Expect a wait at peak lunch.',
      },
      {
        id: 'paloma',
        name: 'Paloma',
        tagline: 'Upscale New Mexican.',
        description: "A upscale Mexican restaurant with thoughtful cooking, good drinks, and a room that feels like a special occasion without being stuffy. If you're looking for one good dinner out in Santa Fe, this is a strong answer.",
        illustration: '/illustrations/listings/paloma.svg',
        photo: '/images/activities/Paloma.avif',
        practical: 'Reservations recommended, especially on weekends.',
      },
      {
        id: 'ras-rhodys',
        name: "Ras Rhody's",
        tagline: 'Vegan Jamaican food truck.',
        description: "A food truck serving vegan Jamaican food from the owner's front yard. Menu rotates daily but always slaps. The type of meal that leaves you feeling alive.",
        illustration: '/illustrations/listings/ras-rhodys.svg',
        photo: "/images/activities/Ras Rhody's.webp",
        practical: 'Food truck — check social media before going.',
      },
      {
        id: 'la-choza',
        name: 'La Choza',
        tagline: "The Shed's less-touristy sister.",
        description: "Owned by the same family as The Shed and serving the same New Mexican food, but without the Plaza location and without the wait. The red and green chile are equally good.",
        illustration: '/illustrations/listings/la-choza.svg',
        photo: '/images/activities/La Choza.jpg',
        practical: 'On Alarid St, near the Railyard. Closed Sundays.',
      },
      {
        id: 'kakawa',
        name: 'Kakawa Chocolate House',
        tagline: 'Drinking chocolate.',
        description: "Kakawa specializes in historically researched drinking chocolates — Aztec, Mayan, Colonial, European. It's unusual, it's small, and the chocolate is really good.",
        illustration: '/illustrations/listings/kakawa.svg',
        photo: '/images/activities/Kakawa Chocolate House.jpg',
        practical: 'Small shop on Canyon Road. Worth combining with a gallery walk.',
      },
    ],
  },
  {
    category: 'Drinks',
    spotIllustration: '/illustrations/spot-drinks.svg',
    items: [
      {
        id: 'la-reina',
        name: 'La Reina at El Rey Court',
        tagline: 'The hip bar.',
        description: "Good margaritas, good lighting, and cool vibes. Really lovely location. It's right next to the house Owen lived in senior year of college.",
        illustration: '/illustrations/listings/la-reina.svg',
        photo: '/images/activities/La Reina.jpg',
        practical: 'At El Rey Court on Cerrillos Rd. A short drive from downtown.',
      },
      {
        id: 'the-brake-room',
        name: 'The Brake Room',
        tagline: 'Straight forward bar.',
        description: "A low-key neighborhood bar in the Railyard district serving Santa Fe Brew Co Beer. It's in a historic railyard building that is kind of amazing to be in.",
        illustration: '/illustrations/listings/the-brake-room.svg',
        photo: '/images/activities/The Brake Room.jpg',
        practical: 'In the Railyard. Check hours — can close early on slow nights.',
      },
      {
        id: 'second-street-brewery',
        name: 'Second Street Brewery',
        tagline: 'Local beer, good patio.',
        description: "Some of the best beer you can get. Highly recommend the Chill Pils. Two locations — the Railyard and Rufina Tap Room on the South side of town (near Meow Wolf).",
        illustration: '/illustrations/listings/second-street-brewery.svg',
        photo: '/images/activities/Second Street Brewery.jpg',
        practical: 'Both locations are great.',
      },
      {
        id: 'dragon-room',
        name: 'The Dragon Room',
        tagline: 'Historic moody bar.',
        description: "The bar at the Pink Adobe, one of Santa Fe's oldest restaurants. Dark, eclectic decor, strong drinks. A good spot for a late drink with cool decor.",
        illustration: '/illustrations/listings/dragon-room.svg',
        photo: '/images/activities/The Dragon Room.jpg',
        practical: 'On Old Santa Fe Trail, a short walk from the Plaza.',
      },
      {
        id: 'tonic',
        name: 'Tonic',
        tagline: 'Serious cocktails.',
        description: "One of the better cocktail bars in Santa Fe. Our favorite drink is the Cactus Coke.",
        illustration: '/illustrations/listings/tonic.svg',
        photo: '/images/activities/Tonic.jpg',
        practical: 'Downtown Santa Fe.',
      },
      {
        id: 'arroyo-vino',
        name: 'Arroyo Vino',
        tagline: 'Bottle shop and restaurant.',
        description: "Best bottle shop in Santa Fe with very knowledgeable staff. Also has amazing food for a high end dinner.",
        illustration: '/illustrations/listings/arroyo-vino.svg',
        photo: '/images/activities/Arroyo Vino.webp',
        practical: 'On Old Santa Fe Trail. Reservations recommended for dinner.',
      },
    ],
  },
  {
    category: 'Day Trips',
    spotIllustration: '/illustrations/spot-daytrips.svg',
    items: [
      {
        id: 'bandelier',
        name: 'Bandelier National Monument',
        tagline: 'Ancient cliff dwellings in a canyon.',
        description: "Bandelier preserves the remains of ancestral Puebloan cliff dwellings carved into the volcanic tuff walls of Frijoles Canyon. The main loop trail is easy and takes about 1.5 hours. One of the most accessible and genuinely moving archaeological sites in the country.",
        illustration: '/illustrations/listings/bandelier.svg',
        photo: '/images/activities/Bandelier National Monument.jpg',
        practical: 'About 45 min from Santa Fe. Timed entry required in summer — book at recreation.gov.',
      },
      {
        id: 'ghost-ranch',
        name: 'Ghost Ranch',
        tagline: "Georgia O'Keeffe's home.",
        description: "Georgia O'Keeffe lived and painted here for decades. The landscape is exactly what's in those paintings — red and ochre cliffs, sky that goes on forever. You can hike to the top of Chimney Rock. The drive through the Chama Valley to get there is half the point.",
        illustration: '/illustrations/listings/ghost-ranch.svg',
        photo: '/images/activities/Ghost Ranch.jpg',
        practical: 'About an hour north toward Abiquiu — plan a full day.',
      },
      {
        id: 'taos',
        name: 'Taos',
        tagline: 'Taos Pueblo, the gorge, earthships.',
        description: "Worth a full day. Taos Pueblo is a UNESCO World Heritage Site — a multi-story adobe community that has been continuously inhabited for over a thousand years. The Rio Grande Gorge Bridge is genuinely dramatic: a 650-foot drop into the canyon. The town itself has good galleries and food. The earthships are also amazing.",
        illustration: '/illustrations/listings/taos.svg',
        photo: '/images/activities/Taos.jpg',
        practical: 'About 1.5 hours north of Santa Fe. Plan a full day.',
      },
    ],
  },
]
