export interface Listing {
  id: string
  name: string
  tagline: string
  description: string
  illustration: string
  photo?: string
  practical: string | null
}

export interface ListingCategory {
  category: string
  spotIllustration: string
  items: Listing[]
}

export const listings: ListingCategory[] = [
  {
    category: 'Museums & Culture',
    spotIllustration: '/illustrations/spot-museums.svg',
    items: [
      {
        id: 'folk-art',
        name: 'Museum of International Folk Art',
        tagline: 'One of the best small museums in the country.',
        description: "The collection here — 130,000 objects from 100 countries, displayed in dense, joyful arrangements — is genuinely extraordinary. The main gallery looks like someone's very wise grandmother organized it. Bring two hours minimum.",
        illustration: '/illustrations/listings/folk-art.svg',
        photo: '/images/activities/Museum of International Folk Art.jpg',
        practical: 'On Museum Hill. 15 min drive or bus from downtown.',
      },
      {
        id: 'georgia-okeeffe-museum',
        name: "Georgia O'Keeffe Museum",
        tagline: "The definitive collection. Downtown, unmissable.",
        description: "The only museum in the world dedicated solely to O'Keeffe's work. The permanent collection spans her entire career — the New York abstractions, the New Mexico flowers and skulls and sky. It's smaller than you expect and better than you expect. The building itself is quietly great.",
        illustration: '/illustrations/listings/georgia-okeeffe-museum.svg',
        photo: "/images/activities/Georgia O'Keeffe Museum.jpg",
        practical: 'On Johnson St, a short walk from the Plaza.',
      },
      {
        id: 'santa-fe-opera',
        name: 'Santa Fe Opera',
        tagline: "Open-air opera in the mountains. Yes, it's that good.",
        description: "The open-air theater sits on a ridge with views of the Jemez and Sangre de Cristo ranges. The season runs July through August. If you can get tickets to anything, do it — the tailgate picnics in the parking lot beforehand are half the experience.",
        illustration: '/illustrations/listings/santa-fe-opera.svg',
        photo: '/images/activities/Santa Fe Opera.jpg',
        practical: 'About 20 min north of Santa Fe. Check the schedule at santafeopera.org.',
      },
      {
        id: 'site-santa-fe',
        name: 'SITE Santa Fe',
        tagline: 'Contemporary art that earns it.',
        description: "SITE does contemporary and installation work at a level that punches well above its size. The building is good, the programming is serious. Worth checking what's up during your visit.",
        illustration: '/illustrations/listings/site-santa-fe.svg',
        photo: '/images/activities/SITE Santa Fe.webp',
        practical: 'In the Railyard district. Easy walk from many hotels.',
      },
      {
        id: 'bug-museum',
        name: 'Santa Fe Reptile and Bug Museum',
        tagline: 'Live reptiles, live bugs, genuinely excellent.',
        description: "A small but serious natural history museum with living collections of reptiles and insects. The staff know their animals and will tell you about them at length. Better than its footprint suggests — one of those Santa Fe spots that rewards wandering in without expectations.",
        illustration: '/illustrations/listings/bug-museum.svg',
        photo: '/images/activities/Santa Fe Reptile and Bug Museum.webp',
        practical: 'Downtown Santa Fe. Worth an hour.',
      },
      {
        id: 'photo-eye',
        name: 'photo-eye Bookstore',
        tagline: 'One of the great photography bookstores in the world.',
        description: "photo-eye has been a destination for photography books since 1979. The selection is extraordinary — new releases, rare monographs, out-of-print finds. Even if you don't buy anything, it's the kind of place you want to exist.",
        illustration: '/illustrations/listings/photo-eye.svg',
        photo: '/images/activities/photo-eye Bookstore.jpg',
        practical: 'On Garcia St. Worth an hour.',
      },
      {
        id: 'loretto-chapel',
        name: 'Loretto Chapel',
        tagline: 'The miraculous staircase. Make of that what you will.',
        description: "A small Gothic chapel built in the 1870s, famous for its spiral staircase — a piece of joinery that has no visible means of support and, depending on who you ask, no natural explanation. The chapel is now deconsecrated and operates as a museum. Compact, worth fifteen minutes.",
        illustration: '/illustrations/listings/loretto-chapel.svg',
        photo: '/images/activities/Loretto Chapel.jpg',
        practical: 'A short walk from the Plaza. Small admission fee.',
      },
    ],
  },
  {
    category: 'Outdoors',
    spotIllustration: '/illustrations/spot-outdoors.svg',
    items: [
      {
        id: 'canyon-road',
        name: 'Canyon Road',
        tagline: 'A mile of galleries and gardens.',
        description: "A historic road lined with galleries, studios, and one very good coffee shop. You can spend twenty minutes or four hours. The quality of the art varies enormously — some of it is brilliant. Walk the whole thing.",
        illustration: '/illustrations/listings/canyon-road.svg',
        photo: '/images/activities/Canyon Road.jpg',
        practical: 'Easy walk from downtown. Mostly flat.',
      },
      {
        id: 'diablo-canyon',
        name: 'Diablo Canyon',
        tagline: 'Volcanic basalt, the Rio Grande, almost no one else.',
        description: "A recreation area near Española where the Rio Grande cuts through dark basalt canyon walls. The hike along the river is easy and genuinely beautiful — petroglyphs on the rocks, cottonwoods along the water, an entirely different landscape from downtown Santa Fe. Best hike: follow the river trail north from the main trailhead for as long as you want and turn around.",
        illustration: '/illustrations/listings/diablo-canyon.svg',
        photo: '/images/activities/Diablo Canyon.avif',
        practical: 'About 30 min north of Santa Fe. Bring water and sun protection.',
      },
      {
        id: 'ski-basin',
        name: 'Ski Basin',
        tagline: 'Drive up the mountain. Worth it for the drive alone.',
        description: "The road up to the Santa Fe Ski Basin is one of the best easy drives in New Mexico — you climb from 7,000 to over 10,000 feet in 16 miles through aspen and spruce. There are hiking trails at the top and views in every direction. In July the wildflowers are out.",
        illustration: '/illustrations/listings/ski-basin.svg',
        photo: '/images/activities/Ski Basin.jpg',
        practical: "Drive up Hyde Park Road. Bring layers — it's 20 degrees cooler at the top.",
      },
      {
        id: 'monte-sol',
        name: 'Monte Sol',
        tagline: 'Easy hike, good views back over the city.',
        description: "A relatively short and accessible hike in the foothills south of town with rewarding views of Santa Fe and the Jemez Mountains to the west. Not as dramatic as the Ski Basin trails but much closer in — good for a morning without committing to a long drive.",
        illustration: '/illustrations/listings/monte-sol.svg',
        photo: '/images/activities/Monte Sol.jpg',
        practical: 'Trailhead off Old Santa Fe Trail Rd. 2–3 hours round trip.',
      },
      {
        id: 'ghost-ranch',
        name: 'Ghost Ranch',
        tagline: "O'Keeffe's landscape. One of the most beautiful drives in America.",
        description: "Georgia O'Keeffe lived and painted here for decades. The landscape is exactly what's in those paintings — red and ochre cliffs, sky that goes on forever. You can hike to the top of Chimney Rock. The drive through the Chama Valley to get there is half the point.",
        illustration: '/illustrations/listings/ghost-ranch.svg',
        photo: '/images/activities/Ghost Ranch.jpg',
        practical: 'About an hour north toward Abiquiu — plan a full day.',
      },
      {
        id: 'audubon-center',
        name: 'Randall Davey Audubon Center',
        tagline: 'Birding and trails at the edge of the city.',
        description: "A wildlife sanctuary tucked into the foothills at the top of Canyon Road. The grounds are a mix of riparian habitat and pinon-juniper forest — good birding, easy walking, peaceful. A nice counterpoint to the galleries immediately below it.",
        illustration: '/illustrations/listings/audubon-center.svg',
        photo: '/images/activities/Randall Davey Audubon Center.jpg',
        practical: 'At the top of Canyon Road. Free to walk the grounds.',
      },
    ],
  },
  {
    category: 'Food',
    spotIllustration: '/illustrations/spot-food.svg',
    items: [
      {
        id: 'el-chile-toreado',
        name: 'El Chile Toreado',
        tagline: 'The best green chile in Santa Fe. No argument.',
        description: "A small, unassuming spot that most tourists walk past. Do not walk past it. The green chile cheeseburger is the one. They grow their own chiles. This is the kind of place a city earns over decades.",
        illustration: '/illustrations/listings/el-chile-toreado.svg',
        photo: '/images/activities/El Chile Toreado.webp',
        practical: 'Small, cash-preferred, closes early. Go at lunch.',
      },
      {
        id: 'the-pantry',
        name: 'The Pantry',
        tagline: 'The Santa Fe diner. Been here forever, for good reason.',
        description: "A classic New Mexican diner that has been feeding Santa Fe since 1948. Breakfast all day, huge portions, green and red chile on everything. The huevos rancheros are exactly right. Expect a line on weekend mornings — it moves quickly.",
        illustration: '/illustrations/listings/the-pantry.svg',
        photo: '/images/activities/The Pantry.jpg',
        practical: 'On Cerrillos Rd. Breakfast and lunch only.',
      },
      {
        id: 'izunami',
        name: 'Izanami',
        tagline: 'Japanese izakaya on the mountain. Worth the drive.',
        description: "The restaurant at Ten Thousand Waves serves Japanese izakaya food — small plates, wood-fired things, sake — in a spare, beautiful room that looks out into the pines. It's a good dinner even if you're not staying at the spa. Reservations strongly advised.",
        illustration: '/illustrations/listings/izunami.svg',
        photo: '/images/activities/Izanami.jpg',
        practical: '15 min drive up the mountain. Reserve ahead.',
      },
      {
        id: 'harrys-road-house',
        name: "Harry's Road House",
        tagline: 'New Mexican comfort food. Always correct.',
        description: "Harry's is the place you go when you want green chile on everything and you want it to be good. A Santa Fe institution. The patio is great, the portions are generous, the margaritas are reliable.",
        illustration: '/illustrations/listings/harrys-road-house.svg',
        photo: "/images/activities/Harry's Road House.jpg",
        practical: 'Old Las Vegas Highway — a short drive from downtown.',
      },
      {
        id: 'the-shed',
        name: 'The Shed',
        tagline: 'A historic casita, a long line, worth it.',
        description: "The Shed occupies a courtyard compound from the 17th century and has been serving New Mexican food since 1953. The red chile is famous for a reason. Lunch lines get long — plan around it or go at opening.",
        illustration: '/illustrations/listings/the-shed.svg',
        photo: '/images/activities/The Shed.jpg',
        practical: 'Closed Sundays. Expect a wait at peak lunch.',
      },
      {
        id: 'paloma',
        name: 'Paloma',
        tagline: 'The nice dinner. Actually worth it.',
        description: "A upscale Mexican restaurant that earns its prices — thoughtful cooking, good mezcal program, a room that feels like a special occasion without being stuffy. If you're looking for one good dinner out in Santa Fe, this is a strong answer.",
        illustration: '/illustrations/listings/paloma.svg',
        photo: '/images/activities/Paloma.avif',
        practical: 'Reservations recommended, especially on weekends.',
      },
      {
        id: 'ras-rhodys',
        name: "Ras Rhody's",
        tagline: 'Vegan Jamaican food truck. Better than you think it will be.',
        description: "A food truck serving vegan Jamaican food — jerk jackfruit, rice and peas, plantains — that is genuinely delicious and not a compromise. One of those finds that makes you feel like a local. Check their Instagram for current location and hours.",
        illustration: '/illustrations/listings/ras-rhodys.svg',
        photo: "/images/activities/Ras Rhody's.webp",
        practical: 'Food truck — check location on social media before going.',
      },
      {
        id: 'kakawa',
        name: 'Kakawa Chocolate House',
        tagline: 'Historic drinking chocolates. A very specific pleasure.',
        description: "Kakawa specializes in historically researched drinking chocolates — Aztec, Mayan, Colonial, European. It's unusual, it's small, and it's exactly the kind of thing Santa Fe does well. Worth a stop even if you just get one drink.",
        illustration: '/illustrations/listings/kakawa.svg',
        photo: '/images/activities/Kakawa Chocolate House.jpg',
        practical: 'Small shop on Canyon Road. Worth combining with a gallery walk.',
      },
    ],
  },
  {
    category: 'Drinks',
    spotIllustration: '/illustrations/spot-drinks.svg',
    items: [
      {
        id: 'la-reina',
        name: 'La Reina at El Rey Court',
        tagline: 'The hotel bar Santa Fe deserves.',
        description: "The bar at El Rey Court is one of those places that earns its reputation. Good margaritas, good lighting, the particular pleasure of drinking in a beautifully restored mid-century motor court.",
        illustration: '/illustrations/listings/la-reina.svg',
        photo: '/images/activities/La Reina.jpg',
        practical: 'At El Rey Court on Cerrillos Rd. A short drive from downtown.',
      },
      {
        id: 'the-brake-room',
        name: 'The Brake Room',
        tagline: 'A good bar. Simple as that.',
        description: "A low-key neighborhood bar in the Railyard district that does what a bar should: good drinks, no pretense, interesting people. A reliable spot for a late drink after dinner without feeling like you've wandered into a tourist trap.",
        illustration: '/illustrations/listings/the-brake-room.svg',
        photo: '/images/activities/The Brake Room.jpg',
        practical: 'In the Railyard. Check hours — can close early on slow nights.',
      },
      {
        id: 'second-street-brewery',
        name: 'Second Street Brewery',
        tagline: 'Local beer, good patio.',
        description: "Santa Fe's most beloved local brewery. The beer is solid across the board and the Railyard location has a great outdoor space. A good spot for a relaxed afternoon drink.",
        illustration: '/illustrations/listings/second-street-brewery.svg',
        photo: '/images/activities/Second Street Brewery.jpg',
        practical: 'Railyard location is the best. Opens at 11am daily.',
      },
    ],
  },
  {
    category: 'Wellness',
    spotIllustration: '/illustrations/spot-wellness.svg',
    items: [
      {
        id: 'ten-thousand-waves-spa',
        name: 'Ten Thousand Waves',
        tagline: 'Japanese mountain spa. The private tubs are the move.',
        description: "The spa at Ten Thousand Waves is the reason people make the trip up the mountain even if they're not staying there. The private hot tubs are bookable by the hour and sit in enclosures carved into the hillside with views of the pines. Massages and treatments are excellent. Book well in advance — it fills up.",
        illustration: '/illustrations/listings/ten-thousand-waves-spa.svg',
        photo: '/images/activities/Ten Thousand Waves.jpg',
        practical: '15 min drive up Artist Rd. Reserve online, often weeks ahead.',
      },
    ],
  },
  {
    category: 'Day Trips',
    spotIllustration: '/illustrations/spot-daytrips.svg',
    items: [
      {
        id: 'bandelier',
        name: 'Bandelier National Monument',
        tagline: 'Ancient cliff dwellings in a canyon. An easy day from Santa Fe.',
        description: "Bandelier preserves the remains of ancestral Puebloan cliff dwellings carved into the volcanic tuff walls of Frijoles Canyon. You can climb ladders into the actual rooms. The main loop trail is easy and takes about 1.5 hours. One of the most accessible and genuinely moving archaeological sites in the country.",
        illustration: '/illustrations/listings/bandelier.svg',
        photo: '/images/activities/Bandelier National Monument.jpg',
        practical: 'About 45 min from Santa Fe. Timed entry required in summer — book at recreation.gov.',
      },
    ],
  },
]
